<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="it.IntegrationTest" tests="3" skipped="0" failures="0" errors="0" timestamp="2019-05-20T03:40:29" hostname="38f9d3513258" time="5.511">
  <properties/>
  <testcase name="testTimeoutOnUpdate" classname="it.IntegrationTest" time="4.973"/>
  <testcase name="testList" classname="it.IntegrationTest" time="0.348"/>
  <testcase name="testCircuitBreakerOnShow" classname="it.IntegrationTest" time="0.19"/>
  <system-out><![CDATA[[?[37minfo?[0m] application - Creating Pool for datasource 'default'
[?[37minfo?[0m] p.a.d.HikariCPConnectionPool - datasource [default] bound to JNDI as DefaultDS
[?[37minfo?[0m] a.e.s.Slf4jLogger - Slf4jLogger started
[?[37minfo?[0m] application - Shutting down connection pool.
[?[37minfo?[0m] application - Creating Pool for datasource 'default'
[?[37minfo?[0m] p.a.d.HikariCPConnectionPool - datasource [default] bound to JNDI as DefaultDS
[?[37minfo?[0m] a.e.s.Slf4jLogger - Slf4jLogger started
[?[37minfo?[0m] application - Shutting down connection pool.
[?[37minfo?[0m] application - Creating Pool for datasource 'default'
[?[37minfo?[0m] p.a.d.HikariCPConnectionPool - datasource [default] bound to JNDI as DefaultDS
[?[37minfo?[0m] a.e.s.Slf4jLogger - Slf4jLogger started
[?[31merror?[0m] a.PostAction - Circuit breaker is open!
net.jodah.failsafe.FailsafeException: java.sql.SQLException: Call this to cause the circuit breaker to trip
	at net.jodah.failsafe.SyncFailsafe.call(SyncFailsafe.java:159)
	at net.jodah.failsafe.SyncFailsafe.get(SyncFailsafe.java:56)
	at v1.post.JPAPostRepository.lambda$null$5(JPAPostRepository.java:48)
	at play.db.jpa.DefaultJPAApi.withTransaction(DefaultJPAApi.java:142)
	at play.db.jpa.DefaultJPAApi.withTransaction(DefaultJPAApi.java:100)
	at v1.post.JPAPostRepository.wrap(JPAPostRepository.java:57)
	at v1.post.JPAPostRepository.lambda$get$6(JPAPostRepository.java:48)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Caused by: java.sql.SQLException: Call this to cause the circuit breaker to trip
	at v1.post.JPAPostRepository.lookup(JPAPostRepository.java:61)
	at v1.post.JPAPostRepository.lambda$null$4(JPAPostRepository.java:48)
	at net.jodah.failsafe.SyncFailsafe.call(SyncFailsafe.java:145)
	at net.jodah.failsafe.SyncFailsafe.get(SyncFailsafe.java:56)
	at v1.post.JPAPostRepository.lambda$null$5(JPAPostRepository.java:48)
	at play.db.jpa.DefaultJPAApi.withTransaction(DefaultJPAApi.java:142)
	at play.db.jpa.DefaultJPAApi.withTransaction(DefaultJPAApi.java:100)
	at v1.post.JPAPostRepository.wrap(JPAPostRepository.java:57)
	at v1.post.JPAPostRepository.lambda$get$6(JPAPostRepository.java:48)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
[?[37minfo?[0m] application - Shutting down connection pool.
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
